

# This file was autogenerated by makepython.py. Do not edit.


import browser  #type: ignore
# from shims.typechecks import *

#this file is pulled into quin.py and also as a preamble
#to the user's script

def print(*args):
    """
    Print data to the screen.
    @param args One or more things to print
    """
    #if we send a single thing to print(),
    #brython does not wrap it in a tuple as
    #CPython does.
    if type(args) != list and type(args) != tuple:
        args=[args]
    lst=[]
    for a in args:
        lst.append(str(a))
    tmp = ' '.join(lst)
    browser.self.impl_print(tmp)

TS=None

