import { GeometricObject } from "./Objects/GeometricObject";


export interface NodeState{
    opened: boolean;
    disabled: boolean;
    selected: boolean;
}

//the field names in here are largely dictated by jstree
export class TreeNode{
    id: string;                 //autogenerated if not present
    text: string;               //text to appear on screen        
    icon: string|boolean;       //If icon contains /: Interpreted as path to image
                                //if false: No icon.
                                //else, interpreted as css class to apply to an <i> element
    state: NodeState;           //tells if it's opened, disabled, and/or selected
    children: TreeNode[] = [];
    li_attr: any;               //attributes for the generated li node
    a_attr: any;                //attributes for the generated a node
    //type: string;               //for jstree 'type' plugin. This allows us to
                                //apply icons and such to a group of nodes

    geo: GeometricObject;       //the GeometricObject associated with this tree node

    jstreeID: string;           //the ID that jstree uses for the associated DOM element.
                                //Note that jstree doesn't set the id field if it's not
                                //initially present, so we don't touch that one either.
                                //This field is not set by TreeNode; it is managed
                                //by external code.
                                
    // properties: AnyProperty[] = [];

    //text = the label that appears onscreen.
    //icon = path to the icon we want to use for the node
    constructor(text:string, icon: string, geo: GeometricObject){
        this.text=text;
        this.state = { 
            opened: true,
            disabled: false,
            selected: false
        };
        // this.type=icon;
        this.icon = `./icons/${icon}.svg`;
        // this.icon = icon;
        this.geo=geo;
    }
}